### ISSUE TITLE
[Discussion] Audit TuningSystem in Pitch.Spelling

### ISSUE THREAD

**Issue by jsbean** [dn-m/NotationModel#124]
cc @bwetherfield 

Somewhat recently, a decision was made to inject `TuningSystem` as a generic parameter into `Pitch.Spelling`. The reason for this was to constrain pitch spellings only to domains that are logically related.

I think this was a bit of over-engineering which has made things quite a bit clunkier downstream.

In the past few days, I have been putting together a Swift version of [chord-sequence-chooser](https://github.com/bwetherfield/chord-sequence-chooser). As I have implemented things like `SpelledChord` and the like, the necessity to nail down the `TuningSystem` is annoying, but also problematic.

It is completely reasonable for a piece to contain (and thus require the ability to notationally describe) pitches which exist in multiple concurrent tuning systems (`EDO12`, `JI13`, `ALIEN`).

I think it would be nice to have some type-safety around this, but the way it was done has been more in-the-way than helpful.

**Comment by jsbean** [comment]
(Perhaps everything just seems like an expression problem problem at the moment).

**Comment by bwetherfield** [comment]
I think a related issue is how do you deal with "enharmonics", where in some tuning systems they are the same pitch (equal-tempered situations), and in some tuning systems they might be considered different (just-tempered leading tones?). I will defer to you, @jsbean on whether I am spouting nonsense here!

**Comment by bwetherfield** [comment]
I am wondering to what extent the different `TuningSystem` flavors were conceived to capture granularity of _spelling_ (e.g. be able to represent "in-between notes") rather than a precise granularity of _tuning_ per se...? 
> Does tuning then become an interpretation issue downstream? 

I imagine I am simplifying and that the answer will be something along the lines of "a bit of both", but I thought this might be a helpful line of inquiry to kick things off!

**Comment by jsbean** [comment]
Here is a survey of the `Pitch.Spelling` API introduced here.

```Swift
let c = Pitch.Spelling(.c) // c natural
let eFlat = Pitch.Spelling(.e, .flat)
let aDoubleFlat = Pitch.Spelling(.a, .doubleFlat)
let gQuarterSharp = Pitch.Spelling(.g, .quarterSharp)
let fThreeQuarterFlat = Pitch.Spelling(.f, .threeQuarterFlat)
```

Extending into JI:

```Swift
let seventhPartialAboveC = Pitch.Spelling(.b, .flat, .septimal(-1))
let fourteenOverFiveAboveA = Pitch.Spelling(.e, .flat, .ptolemaic(1), .septimal(-1))
```
