### ISSUE TITLE
[PitchSpeller] Address FlowNetwork performance

### ISSUE THREAD

**Issue by jsbean** [dn-m/NotationModel#138]
@bwetherfield, I've noticed for the last while, the `FlowNetworkTests.testRandomNetwork()` has become very slow. This will obviously be problematic down the line, but for now is an issue as it slows down all testing (by minutes).

I am running some profiling and this can be a forum of discussion about the findings.

**Comment by jsbean** [comment]
It could be interesting to throw in some `PerformanceTesting` tests on here to check the asymptotic ballpark.

**Comment by jsbean** [comment]
The primary issue is that we call `.minimumCut`, `.maximumFlowAndResidualNetwork` many times instead of caching these.

Perhaps we can make them a `lazy` value so that it is only computed once. However, that creates the possibility that a `FlowNetwork` is mutated, and the `.minimumCut` & co. don't get updated.

**Comment by bwetherfield** [comment]
Keep me posted!
