### ISSUE TITLE
[PitchSpeller] Rename Pairable to Pair

### ISSUE THREAD

**Issue by jsbean** [dn-m/NotationModel#58]
@bwetherfield, whaddyathink?

**Comment by bwetherfield** [comment]
Right on! This is consistent with naming conventions for sure (https://softwareengineering.stackexchange.com/questions/263521/swift-protocol-naming-conventions).

I think this is the first of a few sensible renamings / reorganizings!

**Comment by jsbean** [comment]
Yes, exactly!
